#!/usr/bin/env ruby

require 'git-sleep'
require 'httparty'

auth = GitSleep::Authorizer.instance

begin
  response = HTTParty.get(
    'http://www.gitsleep.com/api/need_sleep',
    body: {
      xid: auth.xid
    }
  )
rescue StandardError => _
  puts "Can't connect to gitsleep.com"
  exit 0
end

if response.response.code.to_i == 200
  data = response.parsed_response

  `git notes --ref=gitsleep add -m "On #{data['sleep24']} hours sleep"`
  remotes = `git remote`.split("\n")
  remotes.each do |remote|
    `git push #{remote} refs/notes/* 2> /dev/null`
  end

elsif response.response.code.to_i == 401
  puts "Must first authorize at #{GitSleep::OUR_SITE}"
  puts 'Then run `git sleep authorize`'
else
  # could not communicate with our server
  # uh oh!
end

