#!/usr/bin/env ruby

require 'git-sleep'

comm = GitSleep::Communicator.instance

unless comm.can_connect?
  puts "Can't connect to gitsleep.com"
  exit 0
end

if comm.happy_response?
  `git notes --ref=gitsleep add -m "On #{comm.hours_of_sleep} hours sleep"`
  remotes = `git remote`.split("\n")
  remotes.each do |remote|
    `git push #{remote} refs/notes/* 2> /dev/null`
  end
elsif comm.not_signed_up_response?
  puts comm.not_signed_up_message
end

