#!/usr/bin/env ruby

require 'git-sleep'

comm = GitSleep::Communicator.instance

unless comm.can_connect?
  puts "Can't connect to gitsleep.com"
  exit 0
end

if comm.happy_response?
  if comm.can_commit?
    puts "Great job #{comm.username}! " \
      "You slept #{comm.hours_of_sleep} hours in the last 24 hours"
  else
    puts "You have only slept #{comm.hours_of_sleep} hours in the " \
      "last 24 hours!!\nYou'll have to git some sleep #{ENV['USER']} before" \
      "you can commit again\n(if you're sure you want to commit right now, " \
      'run: git commit --no-verify)'
    exit(1)
  end
elsif comm.not_signed_up_response?
  puts comm.not_signed_up_message
end

